# This workflow will do a health check of MFOS overnight and run the health test cases.

name: Health check

on:
  schedule:
    # schedule the job to runs at 00:00 UTC every day.
    - cron: "0 0 * * *"
  workflow_dispatch: {}
jobs:
  build:
    # running on ubuntu latest version
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # using node 16.x version
        node-version: [16.x]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Use Node.js $${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run Health Check Tests
      # going to server and install packages and then go to functional folder 
      # install the packages and running health check test cases
      run: |
        cd server; \
        npm install; \
        cp src/.mf.config.SAMPLE.json src/.mf.config.json; \
        cd ../functional; \
        npm install; \
        npm run test -- ./tests/health-check.test.mjs
