# This workflow will do a health check of MFOS overnight and run the health test cases.

name: Health check

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Use Node.js $${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run Health Check Tests
      run: |
        cd server; \
        npm install; \
        cp src/.mf.config.SAMPLE.json src/.mf.config.json; \
        cd ../functional; \
        npm install; \
        npm run test -- ./tests/health-check.test.mjs
